name: test-file

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Run the Maven verify phase
        run: mvn clean install
      - name: Run test
        run: mvn test
      - name: maven checkstyle
        run: mvn -B verify checkstyle:checkstyle   